### ISSUE TITLE
Подобрать цветовую схему

### ISSUE THREAD

**Issue by qertis** [Qweeto/landing-page#1]

**Comment by baskovsky** [comment]
https://coolors.co/

**Comment by qertis** [comment]
Первый цвет фиолетовый (подсмотрел у yahoo)
Второй цвет желто-золотой (подсмотрел у snapchat). Скорее даже золотисто-оранжевый

**Comment by qertis** [comment]
Material Design
https://github.com/material-components/material-components-web-components
